using Content.Client.UserInterface.Controls;
using Content.Shared.DeadSpace.Fishing;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.Fishing;

[GenerateTypedNameReferences]
public sealed partial class LavaFishingWindow : FancyWindow
{
    private LavaFishingPhase? _phase;
    private string? _key;

    public LavaFishingWindow()
    {
        RobustXamlLoader.Load(this);
        GoalHint.SetMessage(Loc.GetString("lava-fishing-window-goal"));
        FinishHint.SetMessage(Loc.GetString("lava-fishing-window-finish"));
        CancelButton.OnPressed += _ => Close();
    }

    public void UpdateState(LavaFishingPhase phase, LavaFishingReelState state, float zoneWidth, Color zoneColor, string key)
    {
        var reeling = phase == LavaFishingPhase.Reeling;
        if (_phase != phase || _key != key)
        {
            _phase = phase;
            _key = key;
            StatusLabel.Text = phase switch
            {
                LavaFishingPhase.Bite => Loc.GetString("lava-fishing-window-bite", ("key", key)),
                LavaFishingPhase.Reeling => Loc.GetString("lava-fishing-window-reeling"),
                _ => Loc.GetString("lava-fishing-window-waiting"),
            };
            ControlsHint.SetMessage(Loc.GetString(reeling ? "lava-fishing-window-controls" : "lava-fishing-window-waiting-hint", ("key", key)));
        }
        ReelingBar.Active = reeling;
        ReelingBar.State = state;
        ReelingBar.ZoneWidth = zoneWidth;
        ReelingBar.ZoneColor = zoneColor;
        CatchProgress.Value = reeling ? state.Progress : 0;
        ProgressLabel.Text = Loc.GetString("lava-fishing-window-progress", ("percent", (int) MathF.Round(CatchProgress.Value * 100)));
    }
}
