// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Content.Client.UserInterface.Controls;
using Content.Shared.DeadSpace.NewLife;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.DeadSpace.NewLife;

[GenerateTypedNameReferences]
public sealed partial class NewLifeWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _timing = IoCManager.Resolve<IGameTiming>();
    private NewLifeEuiState? _state;
    private bool _submitting;
    private TimeSpan _nextRefresh;

    public NewLifeWindow()
    {
        RobustXamlLoader.Load(this);
        Rules.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("new-life-rules")));
        AcceptRules.OnToggled += _ => Refresh();
    }

    public void UpdateState(NewLifeEuiState state)
    {
        _state = state;
        _submitting = false;
        Refresh();
    }

    public void SetSubmitting()
    {
        _submitting = true;
        Refresh();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_timing.CurTime < _nextRefresh)
            return;
        _nextRefresh = _timing.CurTime + TimeSpan.FromMilliseconds(100);
        Refresh();
    }

    private void Refresh()
    {
        if (_state == null)
            return;

        var state = _state.State;
        var rulesSeconds = Math.Max(0, (int) Math.Ceiling((_state.ConfirmAt - _timing.CurTime).TotalSeconds));
        string status;
        switch (state.Availability)
        {
            case NewLifeAvailability.Available:
                status = rulesSeconds > 0
                    ? Loc.GetString("new-life-reading", ("seconds", rulesSeconds))
                    : Loc.GetString("new-life-ready");
                break;
            case NewLifeAvailability.Waiting:
                var seconds = Math.Max(0, (int) Math.Ceiling((state.AvailableAt.GetValueOrDefault() - _timing.CurTime).TotalSeconds));
                status = Loc.GetString("new-life-waiting", ("minutes", seconds / 60), ("seconds", (seconds % 60).ToString("D2")));
                break;
            case NewLifeAvailability.Used:
                status = Loc.GetString("new-life-used");
                break;
            default:
                status = Loc.GetString(state.Reason ?? "new-life-unavailable-access");
                break;
        }

        Status.SetMessage(status);
        ConfirmButton.Disabled = _submitting || !AcceptRules.Pressed ||
                                 state.Availability != NewLifeAvailability.Available || rulesSeconds > 0;
    }
}
