// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using System.Numerics;
using Content.Client.DeadSpace.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Atmos;
using Content.Shared.DeadSpace.Atmos.Piping;
using Content.Shared.Temperature;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Content.Shared.Atmos.Components.GasAnalyzerComponent;

namespace Content.Client.DeadSpace.Atmos.UI;

[GenerateTypedNameReferences]
public sealed partial class GasElectrolyzerWindow : FancyWindow
{
    public event Action? ToggleEnabled;

    public GasElectrolyzerWindow()
    {
        RobustXamlLoader.Load(this);

        ToggleButton.OnPressed += _ => ToggleEnabled?.Invoke();
    }

    public void UpdateState(GasElectrolyzerBoundUserInterfaceState state)
    {
        if (!state.Powered)
        {
            StatusLabel.Text = Loc.GetString("gas-electrolyzer-ui-no-power");
            StatusLabel.FontColorOverride = Color.Red;
        }
        else if (state.Enabled)
        {
            StatusLabel.Text = Loc.GetString("gas-electrolyzer-ui-on");
            StatusLabel.FontColorOverride = Color.LimeGreen;
        }
        else
        {
            StatusLabel.Text = Loc.GetString("gas-electrolyzer-ui-off");
            StatusLabel.FontColorOverride = Color.Gray;
        }

        ToggleButton.Text = Loc.GetString(state.Enabled ? "gas-electrolyzer-ui-turn-off" : "gas-electrolyzer-ui-turn-on");

        GenerateGasDisplay(state.Input, InputContainer);
        GenerateGasDisplay(state.Output, OutputContainer);
    }

    private void GenerateGasDisplay(GasMixEntry gasMix, Control parent)
    {
        parent.RemoveAllChildren();

        var panel = new PanelContainer
        {
            VerticalExpand = true,
            HorizontalExpand = true,
            Margin = new Thickness(4),
        };
        panel.AddStyleClass(DeadSpaceStyleClass.Inset);
        var dataContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            VerticalExpand = true,
            Margin = new Thickness(4),
        };

        parent.AddChild(panel);
        panel.AddChild(dataContainer);

        dataContainer.AddChild(MakeRow(
            Loc.GetString("gas-analyzer-window-volume-text"),
            Loc.GetString("gas-analyzer-window-volume-val-text", ("volume", $"{gasMix.Volume:0.##}"))));

        
        dataContainer.AddChild(MakeRow(
            Loc.GetString("gas-analyzer-window-pressure-text"),
            Loc.GetString("gas-analyzer-window-pressure-val-text", ("pressure", $"{gasMix.Pressure:0.00}"))));

        if (gasMix.Pressure > Atmospherics.GasMinMoles)
        {
            dataContainer.AddChild(MakeRow(
                Loc.GetString("gas-analyzer-window-temperature-text"),
                Loc.GetString("gas-analyzer-window-temperature-val-text",
                    ("tempK", $"{gasMix.Temperature:0.0}"),
                    ("tempC", $"{TemperatureHelpers.KelvinToCelsius(gasMix.Temperature):0.0}"))));
        }

        dataContainer.AddChild(new Control { MinSize = new Vector2(0, 10) });

        if (gasMix.Gases == null || gasMix.Gases.Length == 0)
        {
            dataContainer.AddChild(new Label
            {
                Text = Loc.GetString("gas-analyzer-window-no-gas-text"),
                FontColorOverride = DeadSpaceStylePalette.TextMuted,
            });
            return;
        }

        var tableKey = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };
        var tableVal = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };
        var tablePercent = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };

        dataContainer.AddChild(new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Children =
            {
                tableKey,
                new Control { MinSize = new Vector2(10, 0), HorizontalExpand = true },
                tableVal,
                new Control { MinSize = new Vector2(10, 0), HorizontalExpand = true },
                tablePercent,
            },
        });

        var gasBar = new SplitBar
        {
            MinHeight = 30,
            MinBarSize = new Vector2(12, 0),
        };

        dataContainer.AddChild(new Control { MinSize = new Vector2(0, 10), VerticalExpand = true });

        var totalGasAmount = 0f;
        foreach (var gas in gasMix.Gases)
            totalGasAmount += gas.Amount;

        var hasGas = totalGasAmount > 0f;

        tableKey.AddChild(new Label { Text = Loc.GetString("gas-analyzer-window-gas-column-name"), Align = Label.AlignMode.Center });
        tableVal.AddChild(new Label { Text = Loc.GetString("gas-analyzer-window-molarity-column-name"), Align = Label.AlignMode.Center });
        tablePercent.AddChild(new Label { Text = Loc.GetString("gas-analyzer-window-percentage-column-name"), Align = Label.AlignMode.Center });

        tableKey.AddChild(new StripeBack());
        tableVal.AddChild(new StripeBack());
        tablePercent.AddChild(new StripeBack());

        foreach (var gas in gasMix.Gases)
        {
            var color = Color.FromHex($"#{gas.Color}", Color.White);

            tableKey.AddChild(new Label { Text = Loc.GetString(gas.Name) });
            tableVal.AddChild(new Label
            {
                Text = Loc.GetString("gas-analyzer-window-molarity-text", ("mol", $"{gas.Amount:0.00}")),
                Align = Label.AlignMode.Right,
            });
            tablePercent.AddChild(new Label
            {
                Text = hasGas
                    ? Loc.GetString("gas-analyzer-window-percentage-text", ("percentage", $"{(gas.Amount / totalGasAmount * 100):0.0}"))
                    : Loc.GetString("gas-analyzer-window-percentage-text", ("percentage", "0.0")),
                Align = Label.AlignMode.Right,
            });

            gasBar.AddEntry(gas.Amount, color, tooltip: Loc.GetString("gas-analyzer-window-molarity-percentage-text",
                ("gasName", gas.Name),
                ("amount", $"{gas.Amount:0.##}"),
                ("percentage", hasGas ? $"{(gas.Amount / totalGasAmount * 100):0.#}" : "0")));
        }

        dataContainer.AddChild(gasBar);
    }

    private static BoxContainer MakeRow(string label, string value)
    {
        return new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Children =
            {
                new Label { Text = label },
                new Control { MinSize = new Vector2(10, 0), HorizontalExpand = true },
                new Label { Text = value, Align = Label.AlignMode.Right, HorizontalExpand = true },
            },
        };
    }
}
