// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Content.Client.UserInterface.Controls;
using Content.Shared.DeadSpace.Atmos.Piping;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.Atmos.UI;

[GenerateTypedNameReferences]
public sealed partial class GasTemperatureValveWindow : FancyWindow
{
    public event Action<float>? ThresholdChanged;
    public event Action<bool>? ModeToggled;

    private float _maxThreshold = GasTemperatureValveComponent.MaxThreshold;
    private bool _passWhenBelow = true;

    public GasTemperatureValveWindow()
    {
        RobustXamlLoader.Load(this);

        ThresholdInput.OnValueChanged += _ => SetThresholdButton.Disabled = false;

        SetThresholdButton.OnPressed += _ =>
        {
            ThresholdInput.Value = Math.Clamp(ThresholdInput.Value, 0f, _maxThreshold);
            ThresholdChanged?.Invoke(ThresholdInput.Value);
            SetThresholdButton.Disabled = true;
        };

        ModeButton.OnPressed += _ => ModeToggled?.Invoke(!_passWhenBelow);
    }

    public void SetState(float threshold, bool passWhenBelow, float maxThreshold)
    {
        _maxThreshold = maxThreshold;
        _passWhenBelow = passWhenBelow;

        ModeButton.Text = Loc.GetString(passWhenBelow
            ? "gas-temperature-valve-ui-mode-below"
            : "gas-temperature-valve-ui-mode-above");

        if (SetThresholdButton.Disabled)
            ThresholdInput.Value = MathF.Min(threshold, maxThreshold);
    }
}
