using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Numerics;
using Content.Client.DeadSpace.StationAI;
using Content.Client.Pinpointer.UI;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Medical.SuitSensor;
using Content.Shared.Silicons.StationAi;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using Content.Shared.Medical.MapLavaland;

using static Robust.Client.UserInterface.Controls.BoxContainer;
using Robust.Shared.Physics;

namespace Content.Client.Medical.MapLavaland;

[GenerateTypedNameReferences]
public sealed partial class MapLavaLandWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private readonly SharedTransformSystem _transformSystem;

    private readonly SpriteSystem _spriteSystem;
    private Texture? _blipTexture;

    public MapLavaLandWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _transformSystem = _entManager.System<SharedTransformSystem>();
        _spriteSystem = _entManager.System<SpriteSystem>();
        // NavMap.TrackedEntitySelectedAction += SetTrackedEntityFromNavMap;
    }

    public void Set(string stationName, EntityUid? mapUid)
    {
        _blipTexture = _spriteSystem.Frame0(new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_circle.png")));

        if (_entManager.TryGetComponent<TransformComponent>(mapUid, out var xform))
        {
            NavMap.MapUid = xform.GridUid;
        }
        else
            NavMap.Visible = false;

        StationName.AddStyleClass("LabelBig");
        StationName.Text = stationName;
        NavMap.ForceNavMapUpdate();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
    }

    public void SetChunks(MapLavaLandState state, EntityUid owner)
    {
        NavMap.VisitedGrids = state.VisitedGrids;
        NavMap.OldNavMap = state.OldNavMap;
        if (_blipTexture != null && _entManager.TryGetComponent<TransformComponent>(owner, out var xform))
        {
            NavMap.TrackedEntities[_entManager.GetNetEntity(owner)] = new NavMapBlip(xform.Coordinates, _blipTexture, Color.Cyan, true, false);
        }

        NavMap.ForceNavMapUpdate();
    }

    // private void SetTrackedEntityFromNavMap(NetEntity? netEntity)
    // {
    //     var prevTrackedEntity = _trackedEntity;
    //     _trackedEntity = netEntity;

    //     if (_trackedEntity == prevTrackedEntity)
    //         prevTrackedEntity = null;

    //     NavMap.Focus = _trackedEntity;
    //     _tryToScrollToListFocus = true;

    //     UpdateSensorsTable(_trackedEntity, prevTrackedEntity);
    // }


    /// <summary>
    /// Converts the input coordinates to an EntityCoordinates which are in
    /// reference to the grid that the map is displaying. This is a stylistic
    /// choice; this window deliberately limits the rate that blips update,
    /// but if the blip is attached to another grid which is moving, that
    /// blip will move smoothly, unlike the others. By converting the
    /// coordinates, we are back in control of the blip movement.
    /// </summary>
    private EntityCoordinates CoordinatesToLocal(EntityCoordinates refCoords)
    {
        if (NavMap.MapUid != null)
        {
            return _transformSystem.WithEntityId(refCoords, (EntityUid)NavMap.MapUid);
        }
        else
        {
            return refCoords;
        }
    }

}

public sealed class CrewMonitoringButton : Button
{
    public int IndexInTable;
    public NetEntity SuitSensorUid;
    public EntityCoordinates? Coordinates;
}
