using System.Globalization;
using Content.Client.GameTicking.Managers;
using Content.Client.UserInterface.Controls;
using Content.Shared.CrewManifest;
using Content.Shared.Paper;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class PaperInsertDataWindow : FancyWindow
{
    [Dependency] private readonly IEntitySystemManager _systems = default!;

    private readonly ClientGameTicker _ticker;
    private PaperInsertDataResponseMessage? _data;
    private CrewManifestEntry? _selected;
    private long _displayedSecond = -1;

    public event Action? OnRefresh;
    public event Action<string>? OnInsert;

    public PaperInsertDataWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        _ticker = _systems.GetEntitySystem<ClientGameTicker>();

        RefreshButton.OnPressed += _ =>
        {
            SetLoading();
            OnRefresh?.Invoke();
        };
        StationButton.OnPressed += _ => Insert(_data?.StationName);
        TimeButton.OnPressed += _ => Insert(GetDateTime());
        NameButton.OnPressed += _ => Insert(_data?.CharacterName);
        JobButton.OnPressed += _ => Insert(_data?.CharacterJob);
        ManifestSearch.OnTextChanged += _ => RefreshManifest();
        ManifestSearch.OnTextEntered += _ => InsertPerson();
        InsertNameButton.OnPressed += _ => Insert(_selected?.Name);
        InsertJobButton.OnPressed += _ => Insert(_selected?.JobTitle);
        InsertPersonButton.OnPressed += _ => InsertPerson();
        SetLoading();
    }

    public void SetLoading()
    {
        _data = null;
        _selected = null;
        LoadingLabel.Visible = true;
        DataButtons.Visible = false;
        RefreshButton.Disabled = true;
        ManifestSearch.Editable = false;
        ManifestSearch.Text = string.Empty;
        RefreshManifest();
    }

    public void Populate(PaperInsertDataResponseMessage data)
    {
        _data = data;
        LoadingLabel.Visible = false;
        DataButtons.Visible = true;
        RefreshButton.Disabled = false;
        SetValue(StationButton, StationValue, data.StationName);
        SetValue(NameButton, NameValue, data.CharacterName);
        SetValue(JobButton, JobValue, data.CharacterJob);
        TimeValue.Text = GetDateTime();
        ManifestSearch.Editable = data.ManifestStatus == PaperInsertManifestStatus.Available;
        RefreshManifest();
    }

    private static void SetValue(Button button, RichTextLabel label, string? value)
    {
        button.Disabled = string.IsNullOrWhiteSpace(value);
        label.SetMessage(FormattedMessage.FromUnformatted(button.Disabled
            ? Loc.GetString("paper-ui-insert-unknown")
            : value!));
    }

    private void RefreshManifest()
    {
        ManifestRows.RemoveAllChildren();
        _selected = null;
        UpdateInsertButtons();
        ManifestCount.Text = string.Empty;
        ManifestScroll.Visible = false;
        ManifestStatus.Visible = true;

        if (_data == null)
        {
            SetStatus("paper-ui-insert-loading");
            return;
        }

        if (_data.ManifestStatus != PaperInsertManifestStatus.Available)
        {
            SetStatus(_data.ManifestStatus == PaperInsertManifestStatus.RequiresPda
                ? "paper-ui-insert-requires-pda"
                : "paper-ui-insert-unavailable");
            return;
        }

        var query = ManifestSearch.Text.Trim();
        var count = 0;
        var group = new ButtonGroup();
        foreach (var entry in _data.Manifest)
        {
            if (!entry.Name.Contains(query, StringComparison.CurrentCultureIgnoreCase) &&
                !entry.JobTitle.Contains(query, StringComparison.CurrentCultureIgnoreCase))
            {
                continue;
            }

            var row = new Button
            {
                ToggleMode = true,
                Group = group,
                HorizontalExpand = true,
                ToolTip = $"{entry.Name}, {entry.JobTitle}",
            };
            row.AddChild(new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(4, 2),
                Children =
                {
                    new Label { Text = entry.Name, ClipText = true, MouseFilter = MouseFilterMode.Ignore },
                    new Label
                    {
                        Text = entry.JobTitle,
                        ClipText = true,
                        StyleClasses = { "LabelSecondaryColor" },
                        MouseFilter = MouseFilterMode.Ignore,
                    },
                },
            });
            row.OnPressed += _ =>
            {
                _selected = entry;
                UpdateInsertButtons();
            };
            ManifestRows.AddChild(row);
            count++;
        }

        ManifestCount.Text = Loc.GetString("paper-ui-insert-count", ("shown", count), ("total", _data.Manifest.Count));
        ManifestScroll.Visible = count > 0;
        ManifestStatus.Visible = count == 0;
        if (count == 0)
            SetStatus(_data.Manifest.Count == 0 ? "paper-ui-insert-empty" : "paper-ui-insert-no-results");
    }

    private void SetStatus(string key)
    {
        ManifestStatus.SetMessage(FormattedMessage.FromUnformatted(Loc.GetString(key)));
    }

    private void UpdateInsertButtons()
    {
        InsertNameButton.Disabled = string.IsNullOrWhiteSpace(_selected?.Name);
        InsertJobButton.Disabled = string.IsNullOrWhiteSpace(_selected?.JobTitle);
        InsertPersonButton.Disabled = InsertNameButton.Disabled;
    }

    private void InsertPerson()
    {
        if (_selected is not { } selected)
            return;

        Insert(string.IsNullOrWhiteSpace(selected.JobTitle) ? selected.Name : $"{selected.Name}, {selected.JobTitle}");
    }

    private void Insert(string? value)
    {
        if (!string.IsNullOrWhiteSpace(value))
            OnInsert?.Invoke(value);
    }

    private string GetDateTime()
    {
        return $"{_ticker.RoundDuration():hh\\:mm\\:ss} {DateTime.UtcNow.AddHours(3).ToString("dd.MM", CultureInfo.InvariantCulture)}.2710";
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        var second = (long) _ticker.RoundDuration().TotalSeconds;
        if (!IsOpen || second == _displayedSecond)
            return;

        _displayedSecond = second;
        TimeValue.Text = GetDateTime();
    }
}
